using UnityEngine;
using UnityEditor;
using ZombieGame.Data;
using ZombieGame.Interaction;
using FishNet.Object;
using System.IO;

public class AutoDataCreator : EditorWindow
{
    [MenuItem("Zombie Game/Auto-Create ALL Loot PREFABS")]
    public static void CreateAllLootPrefabs()
    {
        string dataFolder = "Assets/GameData/Items/AutoGenerated";
        string prefabFolder = "Assets/Prefabs/Loot/AutoGenerated";
        
        EnsureFolder(dataFolder);
        EnsureFolder(prefabFolder);

        // 1. Rusty Axe
        ProcessWeapon("Axe", "Ржавый топор", WeaponType.MeleeBlade, dataFolder, prefabFolder, "rusty+axe", "axe");
        // 2. Knife
        ProcessWeapon("Knife", "Окровавленный нож", WeaponType.MeleeBlade, dataFolder, prefabFolder, "bloodied+knife", "knife");
        // 3. Handgun
        ProcessWeapon("Handgun", "Пистолет", WeaponType.Firearm, dataFolder, prefabFolder, "handgun", "pistol");
        // 4. Jacket
        ProcessClothing("TacticalJacket", "Тактическая куртка", EquipSlot.Torso, dataFolder, prefabFolder, "tactical+jacket", "jelet");
        // 5. Backpack
        ProcessClothing("TacticalBackpack", "Тактический рюкзак", EquipSlot.Back, dataFolder, prefabFolder, "backpack", "backpack");
        
        // 6. Медицина (Бинты)
        ProcessConsumable("Bandage", "Чистый бинт", dataFolder, prefabFolder, "bandage");
        ProcessConsumable("BandageBlood", "Грязный бинт", dataFolder, prefabFolder, "bandage_blood");

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("✅ Готово! Проверьте папку AutoGenerated.");
    }

    private static void EnsureFolder(string path)
    {
        if (!AssetDatabase.IsValidFolder(path))
        {
            string[] parts = path.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                if (!AssetDatabase.IsValidFolder(current + "/" + parts[i]))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }
                current += "/" + parts[i];
            }
        }
    }

    private static void ProcessWeapon(string id, string name, WeaponType type, string dataFolder, string prefabFolder, string modelSearch, string iconSearch)
    {
        string dataPath = $"{dataFolder}/{id}.asset";
        WeaponData data = AssetDatabase.LoadAssetAtPath<WeaponData>(dataPath);
        if (data == null)
        {
            data = ScriptableObject.CreateInstance<WeaponData>();
            data.itemID = id; data.itemName = name; data.weaponType = type;
            data.weight = 2.0f;
            AssetDatabase.CreateAsset(data, dataPath);
        }
        CreatePrefabFromModel(id, data, prefabFolder, modelSearch, iconSearch);
    }

    private static void ProcessClothing(string id, string name, EquipSlot slot, string dataFolder, string prefabFolder, string modelSearch, string iconSearch)
    {
        string dataPath = $"{dataFolder}/{id}.asset";
        ClothingData data = AssetDatabase.LoadAssetAtPath<ClothingData>(dataPath);
        if (data == null)
        {
            data = ScriptableObject.CreateInstance<ClothingData>();
            data.itemID = id; data.itemName = name; data.equipSlot = slot;
            data.weight = 1.0f;
            AssetDatabase.CreateAsset(data, dataPath);
        }
        CreatePrefabFromModel(id, data, prefabFolder, modelSearch, iconSearch);
    }

    private static void ProcessConsumable(string id, string name, string dataFolder, string prefabFolder, string iconSearch)
    {
        string dataPath = $"{dataFolder}/{id}.asset";
        ConsumableData data = AssetDatabase.LoadAssetAtPath<ConsumableData>(dataPath);
        if (data == null)
        {
            data = ScriptableObject.CreateInstance<ConsumableData>();
            data.itemID = id; data.itemName = name;
            data.weight = 0.1f;
            AssetDatabase.CreateAsset(data, dataPath);
        }
        
        AttachIcon(id, data, iconSearch);
        EditorUtility.SetDirty(data);
    }

    private static void AttachIcon(string id, ItemData data, string iconSearch)
    {
        string[] allPngs = Directory.GetFiles("Assets", "*.png", SearchOption.AllDirectories);
        string iconPath = null;
        foreach(string f in allPngs)
        {
            if (f.Replace("\\", "/").ToLower().Contains(iconSearch.ToLower()))
            {
                iconPath = f.Replace("\\", "/");
                break;
            }
        }

        if (iconPath != null)
        {
            Sprite iconSprite = AssetDatabase.LoadAssetAtPath<Sprite>(iconPath);
            if (iconSprite != null) data.icon = iconSprite;
        }
        else
        {
            Debug.Log($"Иконка '{iconSearch}' для {id} не найдена, пропускаем.");
        }
    }

    private static void CreatePrefabFromModel(string id, ItemData data, string prefabFolder, string modelSearch, string iconSearch)
    {
        AttachIcon(id, data, iconSearch);

        string prefabPath = $"{prefabFolder}/{id}.prefab";
        if (AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath) != null) return; // Уже есть

        // ЖЕСТКИЙ ПОИСК FBX (Игнорируя баги фильтров Unity)
        string[] allFbx = Directory.GetFiles("Assets", "*.fbx", SearchOption.AllDirectories);
        string fbxPath = null;
        foreach(string f in allFbx)
        {
            if (f.Replace("\\", "/").ToLower().Contains(modelSearch.ToLower()))
            {
                fbxPath = f.Replace("\\", "/");
                break;
            }
        }

        if (fbxPath == null)
        {
            Debug.LogWarning($"FBX файл для '{id}' (поиск по '{modelSearch}') не найден! Проверьте папку с 3D моделью.");
            return;
        }
        
        GameObject modelPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(fbxPath);

        GameObject root = new GameObject(id);
        
        root.AddComponent<NetworkObject>();
        BoxCollider col = root.AddComponent<BoxCollider>();
        PickupItem pickup = root.AddComponent<PickupItem>();
        pickup.itemData = data;

        GameObject childModel = (GameObject)PrefabUtility.InstantiatePrefab(modelPrefab);
        childModel.transform.SetParent(root.transform);
        childModel.transform.localPosition = Vector3.zero;

        col.size = new Vector3(0.5f, 0.5f, 0.5f); 

        GameObject savedPrefab = PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);

        data.prefab = savedPrefab;
        EditorUtility.SetDirty(data);
    }
}
