using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using Zomboid.Data.Items;
using Zomboid.Data.Items.Components;

namespace Zomboid.Editor.Items
{
    public class CSVItemImporter : EditorWindow
    {
        [MenuItem("Zomboid/Import Items from CSV")]
        public static void ImportItems()
        {
            string csvPath = "Docs/Items.csv";
            if (!File.Exists(csvPath))
            {
                Debug.LogError($"CSV not found at {csvPath}. Please ensure it's placed in the root Docs folder.");
                return;
            }

            string[] lines = File.ReadAllLines(csvPath);
            if (lines.Length <= 1) return;

            string savePath = "Assets/_Game/Data/Resources/Items/AutoGenerated";
            if (!AssetDatabase.IsValidFolder(savePath))
            {
                string[] folders = savePath.Split('/');
                string currentPath = folders[0];
                for (int i = 1; i < folders.Length; i++)
                {
                    if (!AssetDatabase.IsValidFolder(currentPath + "/" + folders[i]))
                    {
                        AssetDatabase.CreateFolder(currentPath, folders[i]);
                    }
                    currentPath += "/" + folders[i];
                }
            }

            int createdCount = 0;

            // Пропускаем первую строку (заголовок)
            for (int i = 1; i < lines.Length; i++)
            {
                string line = lines[i];
                if (string.IsNullOrWhiteSpace(line)) continue;

                // Парсим CSV (учитываем, что разделитель ';')
                string[] cols = line.Split(';');
                if (cols.Length < 11) continue;

                string category = cols[1].Trim();
                string subCategory = cols[2].Trim();
                string nameRU = cols[3].Trim();
                string nameEN = cols[4].Trim();
                string modelType = cols[6].Trim();
                string weightStr = cols[10].Trim().Replace(",", ".");

                // Пропускаем объекты мира, которые явно не инвентарные предметы (опционально)
                if (modelType == "Мебель / объект мира" || modelType == "Модуль здания / постройка" || modelType == "Машина")
                    continue;

                string id = nameEN.Replace(" ", "_").Replace("-", "_").ToLower();
                if (string.IsNullOrEmpty(id)) continue;

                string assetPath = $"{savePath}/{id}.asset";
                
                ItemDefinition def = AssetDatabase.LoadAssetAtPath<ItemDefinition>(assetPath);
                bool isNew = false;
                
                if (def == null)
                {
                    def = ScriptableObject.CreateInstance<ItemDefinition>();
                    isNew = true;
                }

                def.Id = id;
                def.NameKey = $"item_name_{id}";
                def.DescriptionKey = $"item_desc_{id}";
                def.EditorName = nameRU;
                def.EditorDescription = $"Category: {category}\nSubcategory: {subCategory}";

                // Маппинг категории
                if (category.Contains("Оружие") || category.Contains("Огнестрел")) def.Category = ItemCategory.Weapon;
                else if (category.Contains("Медицина")) def.Category = ItemCategory.Medicine;
                else if (category.Contains("Еда") || category.Contains("Кухня")) def.Category = ItemCategory.Food;
                else if (category.Contains("Материалы") || category.Contains("Инструменты") || category.Contains("Выживание")) def.Category = ItemCategory.Craft;
                else def.Category = ItemCategory.None;

                if (float.TryParse(weightStr, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out float w))
                {
                    def.Weight = w;
                }

                // --- ЛОГИКА ДОБАВЛЕНИЯ КОМПОНЕНТОВ ---
                // Очищаем старые компоненты (если нужно полностью перезаписать)
                // def.Components.Clear();

                // Добавляем WeaponComponent для оружия
                if (category.Contains("Оружие") || category.Contains("Огнестрел"))
                {
                    if (!def.HasComponent<ItemWeaponComponent>())
                    {
                        var wpn = new ItemWeaponComponent();
                        wpn.Type = category.Contains("Огнестрел") ? ItemWeaponType.Ranged : ItemWeaponType.Melee;
                        def.Components.Add(wpn);
                    }
                }

                // Добавляем FoodComponent для еды
                if (category == "Еда")
                {
                    if (!def.HasComponent<FoodComponent>())
                    {
                        var food = new FoodComponent();
                        def.Components.Add(food);
                    }
                }

                // Добавляем MedicalComponent для медицины
                if (category == "Медицина")
                {
                    if (!def.HasComponent<MedicalComponent>())
                    {
                        var med = new MedicalComponent();
                        def.Components.Add(med);
                    }
                }

                // Добавляем ClothingComponent для одежды
                if (category == "Одежда" || modelType.Contains("Одежда"))
                {
                    if (!def.HasComponent<ClothingComponent>())
                    {
                        var cloth = new ClothingComponent();
                        if (subCategory.ToLower().Contains("головн")) cloth.Slot = ClothingSlot.Head;
                        else if (subCategory.ToLower().Contains("штаны")) cloth.Slot = ClothingSlot.Legs;
                        else if (subCategory.ToLower().Contains("обувь")) cloth.Slot = ClothingSlot.Feet;
                        def.Components.Add(cloth);
                    }
                }

                // Добавляем сумку
                if (modelType.Contains("Сумка"))
                {
                    if (!def.HasComponent<ClothingComponent>())
                    {
                        var cloth = new ClothingComponent();
                        cloth.Slot = ClothingSlot.Backpack;
                        def.Components.Add(cloth);
                    }
                }

                if (isNew)
                {
                    AssetDatabase.CreateAsset(def, assetPath);
                    createdCount++;
                }
                else
                {
                    EditorUtility.SetDirty(def);
                }
            }

            AssetDatabase.SaveAssets();
            
            // --- АВТОГЕНЕРАЦИЯ ФАЙЛА ЛОКАЛИЗАЦИИ ---
            string locFolder = "Assets/_Game/Data/Resources/Localization";
            if (!AssetDatabase.IsValidFolder(locFolder))
            {
                AssetDatabase.CreateFolder("Assets/_Game/Data/Resources", "Localization");
            }
            
            string locCsvPath = $"{locFolder}/Translations.csv";
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("Key;EN;RU;DE;FR"); // Заголовки
            
            for (int i = 1; i < lines.Length; i++)
            {
                string line = lines[i];
                if (string.IsNullOrWhiteSpace(line)) continue;

                string[] cols = line.Split(';');
                if (cols.Length < 11) continue;

                string nameRU = cols[3].Trim();
                string nameEN = cols[4].Trim();
                string modelType = cols[6].Trim();

                if (modelType == "Мебель / объект мира" || modelType == "Модуль здания / постройка" || modelType == "Машина")
                    continue;

                string id = nameEN.Replace(" ", "_").Replace("-", "_").ToLower();
                if (string.IsNullOrEmpty(id)) continue;
                
                // Строка перевода для Названия: Ключ; EN; RU; (пусто); (пусто)
                sb.AppendLine($"item_name_{id};{nameEN};{nameRU};;");
                // Можно добавить описания (пока пустые)
                sb.AppendLine($"item_desc_{id};;;;");
            }
            
            File.WriteAllText(locCsvPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[CSV Importer] Successfully imported/updated {createdCount} items to {savePath}!");
            Debug.Log($"[CSV Importer] Auto-generated localization file at {locCsvPath}!");
        }
    }
}
