using UnityEngine;
using UnityEditor;
using Zomboid.Data.Items;
using Zomboid.Sim.Inventory;
using FishNet.Object;
using System.IO;

namespace Zomboid.Editor.Items
{
    public static class ItemPrefabGenerator
    {
        private const string PrefabSavePath = "Assets/_Game/Prefabs/Items/AutoGenerated";

        [MenuItem("Zomboid/Generate Missing Item Prefabs")]
        public static void GeneratePrefabs()
        {
            if (!AssetDatabase.IsValidFolder(PrefabSavePath))
            {
                Directory.CreateDirectory(PrefabSavePath);
                AssetDatabase.Refresh();
            }

            // Находим все сгенерированные ItemDefinition
            string[] guids = AssetDatabase.FindAssets("t:ItemDefinition", new[] { "Assets/_Game/Data/Resources/Items" });
            int createdCount = 0;

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                ItemDefinition def = AssetDatabase.LoadAssetAtPath<ItemDefinition>(path);
                
                if (def == null) continue;

                // Если префаб уже назначен, пропускаем, чтобы не затереть ручную работу
                if (def.WorldPrefab != null)
                {
                    // Но можно проверить, есть ли на нем нужные компоненты
                    EnsureComponents(def.WorldPrefab, def.Id);
                    continue;
                }

                // Создаем базовый кубик (с коллайдером)
                GameObject tempObj = GameObject.CreatePrimitive(PrimitiveType.Cube);
                tempObj.name = $"Prefab_{def.Id}";
                tempObj.transform.localScale = new Vector3(0.3f, 0.3f, 0.3f); // Делаем его поменьше, как предмет

                // Добавляем сеть и логику
                tempObj.AddComponent<NetworkObject>();
                var worldItem = tempObj.AddComponent<WorldItem>();
                worldItem.DefinitionId = def.Id;

                // Сохраняем как префаб
                string prefabPath = $"{PrefabSavePath}/{def.Id}.prefab";
                GameObject savedPrefab = PrefabUtility.SaveAsPrefabAsset(tempObj, prefabPath);

                // Удаляем временный объект со сцены
                GameObject.DestroyImmediate(tempObj);

                // Привязываем префаб к дефинишну
                def.WorldPrefab = savedPrefab;
                EditorUtility.SetDirty(def);
                createdCount++;
            }

            AssetDatabase.SaveAssets();
            Debug.Log($"[Prefab Generator] Успешно создано {createdCount} новых префабов для предметов!");
        }

        private static void EnsureComponents(GameObject prefab, string defId)
        {
            bool modified = false;
            
            // Загружаем сам ассет префаба для модификации
            string path = AssetDatabase.GetAssetPath(prefab);
            using (var editingScope = new PrefabUtility.EditPrefabContentsScope(path))
            {
                var root = editingScope.prefabContentsRoot;
                
                if (root.GetComponent<NetworkObject>() == null)
                {
                    root.AddComponent<NetworkObject>();
                    modified = true;
                }

                var worldItem = root.GetComponent<WorldItem>();
                if (worldItem == null)
                {
                    worldItem = root.AddComponent<WorldItem>();
                    worldItem.DefinitionId = defId;
                    modified = true;
                }
                else if (string.IsNullOrEmpty(worldItem.DefinitionId))
                {
                    worldItem.DefinitionId = defId;
                    modified = true;
                }
                
                if (root.GetComponent<Collider>() == null)
                {
                    root.AddComponent<BoxCollider>();
                    modified = true;
                }
            }
            
            if (modified)
            {
                Debug.Log($"[Prefab Generator] Обновлены компоненты на существующем префабе: {prefab.name}");
            }
        }
    }
}
